environment:
  matrix:
    - nodejs_version: '14'
install:
  - yarn
test_script:
  - yarn test
build: off
before_test:
  - SET PGUSER=postgres
  - SET PGPASSWORD=pgAdmin4
  - PATH=C:\Program Files\PostgreSQL\14\bin\;%PATH%
  - createdb testdb
services:
  - postgresql101
